name: Static Code Analysis

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  static-analysis:
    name: Security & Code Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-static-analysis-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-static-analysis-
    
    - name: Install analysis tools
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    
    - name: Run gosec security scanner
      run: gosec ./...
      continue-on-error: true
    
    - name: Run comprehensive static analysis
      run: golangci-lint run
      continue-on-error: true